markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: GaYuu's Blog
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: GaYuu's Blog
url: http://github.gayuus.io/
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: index.html
  - text: 分类目录 
    url: categories.html
  - text: 文章归档
    url: archives.html
  - text: 联系我
    url: contact.html
  - text: 友情链接
    url: links.html

#Author config
author:
    name: GaYuus
    email: admin@gayuus.com
    imageLink: http://tp1.sinaimg.cn/2532112564/180/40041395527/0
    simpleIntro: 我是「GaYuus」，未拿起便放下，未爱过便失恋。
    detailIntro:
      <p>一个国内不知名的Romer，常年混迹互联网中，无名小辈，关注移动设备和移动互联网。曾学过点C语言，写过几个渣渣的安卓程序，热爱开源分享。目前在广东某个小城市高中读书(学渣伤不起)，由于没有妹纸，我都开始怀疑我是不是Gay了。曾泡了几个月妹纸，结果泡成了男闺蜜。人称“二货”。</p>
      <p>很早之前，搭建过各种博客，但由于各种原因都没有维护下去。这次购买了域名，并使用Jekyll来写博客，托管在Github Pages上，使用的主题是Kunka，希望这次不会半途而废。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/gayuus
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/gayuus
  - class: icon-twitter
    url: http://twitter.com
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 芦苇丛的鹅蛋
      url: http://flau.me
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  url: gayuus.com
  id: UA-46524889-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: gayuus
